name: "Pulse CI"

on: 
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - '*'

jobs:
  ios-latest:
    name: Unit Tests (iOS 15.2, Xcode 13.2)
    runs-on: macOS-11
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.2.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        run: Scripts/test.sh -d "OS=15.2,name=iPhone 13 Pro"
  macos-latest:
    name: Unit Tests (macOS, Xcode 13.2)
    runs-on: macOS-11
    env: 
      DEVELOPER_DIR: /Applications/Xcode_13.2.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        run: Scripts/test.sh -d "arch=x86_64"
  tvos-latest:
    name: Unit Tests (macOS, Xcode 13.2)
    runs-on: macOS-11
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.2.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        run: Scripts/test.sh -d "OS=15.2,name=Apple TV 4K"
  watchos-latest:
    name: Build (watchOS 7.4, Xcode 13.2)
    runs-on: macOS-11
    env: 
      DEVELOPER_DIR: /Applications/Xcode_12.5.1.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: Scripts/build.sh -d "OS=7.4,name=Apple Watch Series 6 - 44mm"
  ios-xcode-12:
    name: Unit Tests (iOS 14.2, Xcode 12.5.1)
    runs-on: macOS-11
    env:
      DEVELOPER_DIR: /Applications/Xcode_12.5.1.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        run: Scripts/test.sh -d "OS=14.5,name=iPhone 12"
  swift-build:
    name: Swift Build (SPM)
    runs-on: macOS-11
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.2.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: swift build
  discover-typos:
    name: Discover Typos
    runs-on: macOS-11
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.2.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: Discover typos
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install codespell
          codespell --ignore-words-list="hart,inout,msdos,sur" --skip="./.build/*"
